name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.tf'

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
          TF_VAR_jamfpro_basic_auth_username: ${{ secrets.JAMF_USERNAME }}
          TF_VAR_jamfpro_basic_auth_password: ${{ secrets.JAMF_PASSWORD }}
          TF_VAR_jamfpro_instance_fqdn: ${{ secrets.JAMF_URL }}
